spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vanopt
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8080
