spring.application.name=vanopt
spring.datasource.url=jdbc:postgresql://localhost:5432/vanopt
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true